theme: jekyll-swiss
markdown: GFM
exclude:
  - goaway
  
# jekyll-swiss
# jekyll-theme-primer
# jekyll-theme-architect
# jekyll-theme-cayman
# jekyll-theme-dinky
# jekyll-theme-hacker
# jekyll-theme-leap-day
# jekyll-theme-merlot WORKS
# jekyll-theme-midnight
# jekyll-theme-minimal
# jekyll-theme-modernist
# jekyll-theme-slate
# jekyll-theme-tactile
# jekyll-theme-time-machine
