theme: jekyll-theme-hacker
markdown: GFM
exclude:
  - goaway
  
# jekyll-swiss - does not work, generic error
# jekyll-theme-primer WORKS
# jekyll-theme-architect WORKS
# jekyll-theme-cayman WORKS
# jekyll-theme-dinky WORKS
# jekyll-theme-hacker
# jekyll-theme-leap-day
# jekyll-theme-merlot WORKS
# jekyll-theme-midnight
# jekyll-theme-minimal
# jekyll-theme-modernist
# jekyll-theme-slate
# jekyll-theme-tactile
# jekyll-theme-time-machine
