name: Cat request
  description: Suggest a cat for this website
  labels: [cat-request]
  body:
  - type: input
    id: cat-name
    attributes:
      label: Cat name
      description: "What is this cat's name?"
      placeholder: "e.g. Grumpy Cat"
    validations:
      required: true
  - type: input
    id: cat-name
    attributes:
      label: Cat image
      description: "Where can we find a picture?"
      placeholder: "e.g. http://www.cats.com/grumpy.jpg"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: "Why should we add this cat?"
    validations:
      required: false
